name: storino
description: "STORINO APP MOBILE."
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  google_fonts: ^6.3.3
  injectable: ^2.7.1+2
  shared_preferences: ^2.5.4
  flutter_localization: ^0.3.3
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  modal_progress_hud_nsn: ^0.5.1
  shimmer: ^3.0.0

dev_dependencies:
  #change_app_package_name: ^1.4.0
  #flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/assets_png/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/assets_svg/
    - assets/assets_png/
